---
title: "HW5"
author: "Kevin Neal"
date: "May 12, 2015"
output: 
  html_document:
    fig_caption: yes
    fig_width: 8
    theme: spacelab
    toc: yes
---

```{r init, echo=F, include=F}
require(vioplot) || {install.packages("vioplot"); library(vioplot)}
require(dplyr)
require(tidyr)
require(reshape2)
require(minerva)
require(infotheo)
require(corrplot)

setwd("C:/Users/Kevin/Google Drive/UCLA Courses or Lab meetings etc/PhysciM200/physciM200_psets")

par(mfrow=c(1,1))
```



# Data analysis
## Import data and reformat to contingency table
```{r import hospital data and reformat}
hosp.raw <- read.csv("Hospitals.csv")
head(hosp.raw, 10)
str(hosp.raw)
hosp.raw[,1] <- as.character(hosp.raw[,1]) # changes "Type" column from factors to strings. Change back to factors after conversion...?
unique(hosp.raw[1]) # need to combine MORT, COMP, and SURV by hospital
for (ii in c("COMP", "SURV", "MORT")){
  hosp.raw[grep(ii, as.character(hosp.raw[,1])),1] <- ii # prints the row indices of COMP-; use this to combine all these rows 
}
# want sum of Type, by location...
hosp.raw[,1] <- as.factor(hosp[,1])
hosp <- acast(hosp.raw, Location ~ Type, fun.aggregate=sum, value.var="Counts") # cast "hosp" dataframe with rows corresponding to Location and columns to Type, and summing Counts by their Type that corresponds to a Location. Output is desired contingency table.


colnames(hosp) <- c("Compl", "Dead", "Surv")
colnames(hosp)
hosp.c <- hosp[,c(2,1,3)] # reorder contingency table to Locations, Dead, Complications, Survived
rownames(hosp) <- c("Cedars.Sinai", "Kaiser.LA", "UCLA.Harbor", "UCLA.OliveView", "UCLA.RonaldReagan", "UCLA.SantaMonica") # change rownames
hosp.c <- hosp[c(1,3,4,5,6,2),] # reorder rows to match those on the problem set handout and check accuracy
head(hosp)


```

## Test for associations between hospital location and survival status using Fisher's Exact test
```{r Fisher's exact text}
fisher.test(hosp)
?fisher.test

```


