---
title: "HW6 ANOVA"
author: "Kevin Neal"
date: "due May 19, 2015"
output: 
  html_document:
    fig_caption: yes
    fig_width: 8
    theme: spacelab
    toc: yes
---

```{r init, echo=F, include=F}
require(vioplot) || {install.packages("vioplot"); library(vioplot)}
require(dplyr)
require(tidyr)
require(reshape2)
require(minerva)
require(infotheo)
require(corrplot)

setwd("C:/Users/Kevin/Google Drive/UCLA Courses or Lab meetings etc/PhysciM200/physciM200_psets")

par(mfrow=c(1,1))
```

```{r }

step <- read.csv("steplength.csv", header=T) # short-form data. Could (should?) put into a three-dim array...

steplong <- gather(step, Train, Steplength, 3:22) 
steplong <- melt(data=step, id=c("Treatment", "Train"), value.name="Steplength") # both gather and melt accomplish same thing (gather is a wrapper for melt, apparently); goal was to get long-form data. Seems more intuitive with melt.

#with(steplong, boxplot(Steplength[Treatment=="OEC"]))
?boxplot
steplong2 <- steplong
boxplot(Steplength~Treatment+Train, data=steplong, col=rainbow(4))

steplong[,5] <- with(steplong, ave(Steplength, Train, Treatment, FUN=median))

interact.md <- unique(with(steplong, ave(Steplength, Train, Treatment, FUN=median))) # medians for OT, OU, MT, MU respectively
treat.md <- unique(with(steplong, ave(Steplength, Treatment, FUN=median))) # medians for OEC and MEDIA respectively
train.md <- unique(with(steplong, ave(Steplength, Train, FUN=median))) # medians for Trained and Untrained, respectively

plot(c(1,1,2,2), y=interact.md, xlab="Treatment") # treatment type
lines(c(1,2), c(interact.md[1],interact.md[3]), col="blue")
lines(c(1,2), c(interact.md[2],interact.md[4]), col="red")
lines(c(1,2), c(treat.md[1],treat.md[2]), col="black")

plot(c(1,2,1,2), y=interact.md, xlab="Training") # training type
lines(c(1,2), c(interact.md[1],interact.md[2]), col="forestgreen")
lines(c(1,2), c(interact.md[3],interact.md[4]), col="sienna")
lines(c(1,2), c(train.md[1],train.md[2]), col="black")

```

